### ISSUE TITLE
SSR Manifest Support

### ISSUE THREAD

**Issue by N0tExisting** [owlsdepartment/vite-plugin-dev-manifest#1]

**Comment by F0rsaken** [comment]
@N0tExisting I can try to do it, but it would be nice to have an example of repo or even better a specification of how it should work

**Comment by N0tExisting** [comment]
From what I have seen it seems to be:
```ts
interface SSRManifest {
  [file: string]: string[] // (the emitted files?)
}
```

**Comment by F0rsaken** [comment]
I studied how SSR works in Vite, and you actually need to specify files yourself, just manually point to them. Manifest is generated based on `build.rollupOptions.input` field, so it all comes down to manually defining your inputs. Using this library for that is redundant IMHO
