### ISSUE TITLE
Ability to remove dev manifest file upon dev server closes

### ISSUE THREAD

**Issue by gwainor** [owlsdepartment/vite-plugin-dev-manifest#5]
I use this plugin to integrate Vite with Django.
I check the `manifest.dev.json` file and if exists, I use Vite dev server URL to import into HTML and if it is not exist, I use static file so that I don't have to keep a Vite Dev Server on.

So would you please add an optional ability to remove the dev manifest file when vite server closes?

**Comment by przyb** [comment]
Hi @goztrk, thanks for the idea and for describing your use case. Typically, the Vite dev process is closed by interruption so I’m afraid there won’t be an option to do any action upon that. I’ll take a look into the docs to fact-check that so for now I’m keeping this issue marked as a feature request. 

Have a great day!

**Comment by gwainor** [comment]
Thanks for the feedback @przyb! Actually there is one hook that can be used. It is described in Universal Hooks section of Plugin API in their documentation:
https://vitejs.dev/guide/api-plugin.html#universal-hooks
`closeBundle` hook is being called just before the server closes. That hook is actually a hook of  Rollup: https://rollupjs.org/plugin-development/#closebundle
I think this hook is being called even if server being closed with interruption.

**Comment by F0rsaken** [comment]
@goztrk happy to say that I found a minute to do this. Just upgrade to `1.2.0` and you should be good to go, as I made it as a default behaviour from now on 😄

Thx for a good suggestion!
