### ISSUE TITLE
CJS warning

### ISSUE THREAD

**Issue by sgarcialaguna-mms** [owlsdepartment/vite-plugin-dev-manifest#7]
Steps to reproduce:

- Create a new vite app: `yarn create vite`. Select Vanilla and JavaScript to keep it as simple as possible
- Create a vite.config.js:
```javascript
import { defineConfig } from 'vite';
import devManifest from 'vite-plugin-dev-manifest';

export default defineConfig({
    plugins: [
        devManifest(),
    ],

    build: {
        manifest: true,

        rollupOptions: {
            input: 'src/main.js'
        }
    }
})
```

- Run `vite build` or `vite dev` and you get the following error: 

`failed to load config from C:\Git\personal\dev-manifest\vite.config.js
error when starting dev server:
TypeError: devManifest is not a function`

- You can get around the error by removing `"type": "module"` from the package.json. However, this results in the following warning:

`The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.`

Versions:
Node 20.1.0
Yarn 1.22.19
Vite 5.0.10
vite-plugin-dev-manifest 1.3.0

**Comment by sgarcialaguna-mms** [comment]
I read a little bit into it starting from a Stackoverflow issue (https://stackoverflow.com/questions/42708484/what-is-the-module-package-json-field-for) and it seems like having a "main" and a "module" field" in package.json *should* work. It is not an official standard, but so widespread that it should work anywhere.

The NodeJS way (TM) seems to be conditional exports: (https://nodejs.org/api/packages.html#conditional-exports). I patched this in my node_modules folder and got it to work without errors or warning, but I don't know if this would have unintended side effects.

**Comment by erropix** [comment]
@moonrailgun  Please add the `exports` fields to package.json, it solves the issue:

```json
"exports": {
    ".": "./dist/index.mjs"
},
```

Without this, node will import the cjs as it's set in the `main` field.

**Comment by erropix** [comment]
@sgarcialaguna-mms as a temporary workarround, i had to change the import statement to

```js
import devManifest from 'vite-plugin-dev-manifest/dist/index.mjs';
```

**Comment by F0rsaken** [comment]
thx guys for noticing that, I'm surprised that it wasn't found earlier. I made a patch to `1.3.1`, it should work out of box now. 😄
